services:
    app:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
            target: dev
            args:
                WWWUSER: ${WWWUSER}
                WWWGROUP: ${WWWGROUP}
        restart: always
        container_name: st-app
        working_dir: /var/www
        ports:
            - "8000:8000"
            - "5175:5173"
        volumes:
            - .:/var/www
            - .docker/php/supervisord.conf:/etc/supervisord.conf
            - .docker/php/supervisor.conf:/etc/supervisor/conf.d/supervisor.conf
        depends_on:
            - mysql  # <--- UBAH INI
            - redis
        networks:
            - WebFPTE

    nginx:
        image: nginx:alpine
        container_name: st-nginx
        restart: always
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - WebFPTE

    # --- BAGIAN INI DIUBAH DARI POSTGRES KE MYSQL ---
    mysql:
        image: mysql:8.0
        container_name: st-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: ${DB_DATABASE}
            # Jika user di .env bukan root, baris di bawah ini akan membuat user baru
            # MYSQL_USER: ${DB_USERNAME}
            # MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - WebFPTE
        ports:
            - "3311:3306" # Port default internal
    # -----------------------------------------------

    redis:
        image: redis:alpine
        container_name: st-redis
        restart: always
        volumes:
            - redis_data:/data
        networks:
            - WebFPTE

volumes:
    mysql_data: # <--- UBAH DARI pg_data KE mysql_data
    redis_data:

networks:
    WebFPTE:
        driver: bridge
