services:
  app:
    build:
      target: dev
    environment:
      PHP_IDE_CONFIG: "serverName=stage"
    restart: unless-stopped

  nginx:
    restart: unless-stopped
    ports:
      - "80:80"

  # --- UBAH KE MYSQL ---
  mysql:
    restart: unless-stopped
    ports:
      - "3311:3306" # Akses dari DBeaver/Laptop pakai port 3307
  # ---------------------

  redis:
    restart: unless-stopped
    ports:
      - "6381:6379"
